name: Deploy Main to Render

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Render web service
    runs-on: ubuntu-latest
    steps:     
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}